replicaCount: 1

image:
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ecr-creds

frontend:
  name: dashboard-frontend
  image: 386503255039.dkr.ecr.us-west-2.amazonaws.com/dashboard-frontend
  containerPort: 5000
  service:
    type: ClusterIP
    port: 80
    targetPort: 5000

api:
  name: dashboard-api
  image: 386503255039.dkr.ecr.us-west-2.amazonaws.com/mock-api
  containerPort: 5001
  service:
    type: ClusterIP
    port: 80
    targetPort: 5001

prometheus:
  name: prometheus
  image: prom/prometheus:latest
  containerPort: 9090
  service:
    type: ClusterIP
    port: 80
    targetPort: 9090
  extraScrapeConfigs: |
    - job_name: 'node-exporter'
      static_configs:
        - targets: ['node-exporter.kube-system.svc.cluster.local:9100']

    - job_name: 'kube-state-metrics'
      static_configs:
        - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']

    - job_name: 'cadvisor'
      kubernetes_sd_configs:
        - role: node
      scheme: https
      tls_config:
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
        - source_labels: [__metrics_path__]
          target_label: metrics_path
        - source_labels: [__address__]
          regex: (.+):10250
          target_label: __address__
          replacement: $1:10250
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)

    - job_name: 'kubernetes-apiservers'
      kubernetes_sd_configs:
        - role: endpoints
      relabel_configs:
        - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
          action: keep
          regex: default;kubernetes;https

grafana:
  name: grafana
  image: grafana/grafana:latest
  containerPort: 3000
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000

alertmanager:
  name: alertmanager
  image: 386503255039.dkr.ecr.us-west-2.amazonaws.com/alertmanager
  containerPorts:
    web: 9093
    cluster: 9094
  service:
    type: ClusterIP
    ports:
      web: 80
      cluster: 9094
