# Dockerfile.frontend
FROM python:3.12-slim

WORKDIR /app

COPY app/frontend /app

# Install system packages + Flask + requests
RUN apt-get update && apt-get install -y sshpass && \
    pip install --no-cache-dir flask requests && \
    apt-get clean

EXPOSE 5000

CMD ["python3", "app.py"]