# Dockerfile.mock_api
FROM python:3.12-slim

WORKDIR /app

# Copy backend code
COPY app/backend /app

RUN pip install --no-cache-dir flask flask-cors

EXPOSE 5001

CMD ["python3", "mock_service_api.py"]