FROM python:3.10-slim

WORKDIR /app

COPY firmware-server.py /app/firmware-server.py
COPY requirements.txt /app/requirements.txt
COPY firmware/ /app/firmware/

RUN ls -la /app && pip install --no-cache-dir -r /app/requirements.txt

CMD ["python", "firmware-server.py"]




