apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: {{ .Release.Namespace }}
data:
  grafana.ini: |-
    [server]
    root_url = %(protocol)s://%(domain)s/grafana/
    serve_from_sub_path = true
