global:
  resolve_timeout: 5m

route:
  receiver: log-only
  routes:
    - match:
        alertname: DashboardInactive
      receiver: shutdown-webhook

receivers:
  - name: log-only

  - name: shutdown-webhook
    webhook_configs:
      - url: https://monitor.dtinfra.site/api/stop