global:
  resolve_timeout: 5m

route:
  receiver: shutdown-webhook  # or use routing logic below

receivers:
  - name: "log-only"

  - name: shutdown-webhook
    webhook_configs:
      - url: http://your-api-host/api/stop