global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - scheme: https
      path_prefix: /alertmanager
      static_configs:
        - targets: ["monitor.dtinfra.site"]

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'dashboard-app'
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets: ["monitor.dtinfra.site"]
