global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - scheme: https
      path_prefix: /alertmanager
      static_configs:
        - targets: ["monitor.dtinfra.site"]

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'dashboard-app'
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets: ["monitor.dtinfra.site"]

groups:
  - name: inactivity-rules
    rules:
    - alert: DashboardInactive
      expr: rate(request_count{endpoint=~"/sites/.+"}[5m]) < 0.01
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "Dashboard inactive"
        description: "No requests to /sites/... in the last 5 minutes"