{
 "title": "App Monitoring Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "App Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ram Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job!=\"prometheus\"}[$__rate_interval]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Alerts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"pending\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}