company_name: Nintendo
logo_url: assets/nintendo.png 
primary_color: "#e60012"
page_title: "Nintendo Service Health Dashboard"
header_text: "⚙️ Mushroom Metrics"
dashboard_url: "http://dashboard-alb-2077270126.us-west-2.elb.amazonaws.com/grafana"
