company_name: Adobe
logo_url: assets/adobe.png
primary_color: "#007acc"
page_title: "Adobe Service Health Dashboard"
header_text: "⚙ Adobe Service Monitor"
dashboard_url: "http://dashboard-alb-2077270126.us-west-2.elb.amazonaws.com/grafana"
