company_name: Adobe
logo_url: assets/adobe.png
primary_color: "#FF0000"
page_title: "Adobe Service Health Dashboard"
header_text: "🚀 Cloud Reliability Dashboard – Adobe Creative Services"
dashboard_url: "http://dashboard-alb-2077270126.us-west-2.elb.amazonaws.com/grafana"
