company_name: Nintendo
logo_url: assets/nintendo.png 
primary_color: "#e60012"
page_title: "Nintendo Service Health Dashboard"
header_text: "⚙️ Mushroom Metrics"
dashboard_url: "https://grafana.nintendo.mock/grafana/d/health"
