company_name: Other
logo_url: assets/other.png 
primary_color: "#007acc"
page_title: "Service Health Dashboard"
header_text: "⚙ Service Monitor"
dashboard_url: "http://dashboard-alb-2077270126.us-west-2.elb.amazonaws.com/grafana"
