company_name: Meta
logo_url: assets/meta.png 
primary_color: "#1877f2"
page_title: "Meta Service Health Dashboard"
header_text: "⚙️ Meta Grid"
dashboard_url: "http://dashboard-alb-2077270126.us-west-2.elb.amazonaws.com/grafana"
