apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.firmwareServer.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.firmwareServer.name }}-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.firmwareServer.name }}-binding
roleRef:
  kind: Role
  name: {{ .Values.firmwareServer.name }}-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ .Values.firmwareServer.name }}
