apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}
spec:
  selector:
    app: {{ .Values.api.name }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.containerPort }}
  type: {{ .Values.api.service.type }}