apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.car.name }}
spec:
  selector:
    app: {{ .Values.car.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.car.containerPort }}
  type: ClusterIP
