apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.firmwareServer.name }}
spec:
  selector:
    app: {{ .Values.firmwareServer.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.firmwareServer.containerPort }}
  type: ClusterIP
