apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.grafana.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.grafana.name }}
  ports:
    - name: web
      port: {{ .Values.grafana.service.port }}
      targetPort: {{ .Values.grafana.containerPort }}
      nodePort: {{ .Values.grafana.service.nodePort }}
  type: {{ .Values.grafana.service.type }}