apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: staging
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - name: http
      port: 80
      targetPort: 9090
  type: ClusterIP


